-- CRIAR TABELA PARA PROFISSIONAIS
CREATE TABLE Profissional(
	Id SERIAL,
	Cpf VARCHAR(50),
	Login VARCHAR(70) NOT NULL UNIQUE,
	Nome VARCHAR(255) NOT NULL,
	Senha VARCHAR(255) NOT NULL,
	Grupo VARCHAR(70) NOT NULL,
	CONSTRAINT Profissional_pk PRIMARY KEY(Cpf)
);

-- CRIAR TABELA PARA PACIENTE
CREATE TABLE Paciente(
	Id SERIAL,
	Cpf_paciente VARCHAR(50),
	Nome VARCHAR(255),
	Sus VARCHAR(100) NOT NULL unique,
	Data_de_nascimento DATE NOT NULL,
	email VARCHAR(100) NOT NULL,
	Quadro VARCHAR(50) NOT NULL,
	Descricao VARCHAR(8000),
	TriagemID INTEGER,
	CONSTRAINT Paciente_pk PRIMARY KEY(Cpf_paciente)
);

--CRIAR TABELA TRIAGEM
CREATE TABLE Triagem(
	Id SERIAL,
	Quadro VARCHAR(50) NOT NULL,
	Descricao VARCHAR(8000),
	CONSTRAINT Triagem_pk PRIMARY KEY(Id)
);


-- ALTEREAR TABELA PACIENTE
ALTER TABLE Paciente
ADD CONSTRAINT Paciente_Triagem_fk FOREIGN KEY(TriagemID)
REFERENCES Triagem(Id);





